name: clone_notes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  uuid: ^3.0.7
  flutter_slidable: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true

