// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAijh-qkV4uWXnhbf3n5ho00x4kK7002Q',
    appId: '1:144523942799:android:ae2877d44127a187cf49fa',
    messagingSenderId: '144523942799',
    projectId: 'clone-notes',
    databaseURL: 'https://clone-notes-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clone-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv_4_ildYXGK-NURNrGzbLeN-XGSI9UVo',
    appId: '1:144523942799:ios:e06c79db4f66f767cf49fa',
    messagingSenderId: '144523942799',
    projectId: 'clone-notes',
    databaseURL: 'https://clone-notes-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clone-notes.appspot.com',
    iosClientId: '144523942799-12dt4cjtnr6k4epqq2qbdv6rrhqpqr0c.apps.googleusercontent.com',
    iosBundleId: 'man.cloneNotes',
  );
}
